version: '3'

services:
    web:
        build: docker/web/
        image: matthiasnoback/layers-ports-and-adapters-workshop-web
        volumes:
            - ./:/opt
        ports:
            - 80:8080
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=docker"
        user: ${HOST_UID}:${HOST_GID}

    devtools:
        build: docker/devtools/
        image: matthiasnoback/layers-ports-and-adapters-workshop-devtools
        volumes:
            - ./:/opt
            - ${COMPOSER_HOME}:/home/.composer
        environment:
            COMPOSER_HOME: /home/.composer
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=docker"
        depends_on:
            - web
        user: ${HOST_UID}:${HOST_GID}

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            # management UI:
            - 15672:15672
